### ISSUE TITLE
Import webradio fail

### ISSUE THREAD

**Issue by codeput** [rern/rAudio-addons#2]
Hello, i get this messages when import my webradio:

./importwebradio.sh: line 24: /srv/http/data/webradios/${url//\//|}: ambiguous redirect.

My playlist file is:

[playlist]
File1=http://streams.fluxfm.de/70er/mp3-320/audio/
Title1=FluxFM - 70s
File2=https://www.wwoz.org/listen/hi/
Title2=WWOZ New Orleans FM 90.7 - Various Artists
File3=http://streams.fluxfm.de/80er/mp3-320/streams.fluxfm.de/
Title3=FluxFM - 80s
NumberOfEntries=100

**Comment by rern** [comment]
1 file for 1 station only.
